pages:
 image: node:16.15.0
 stage: deploy
 script:
  - npm install
  - npm run build:prod
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
  - cp public/index.html public/404.html
 artifacts:
  expire_in: 1 day
  paths:
  - public
 only:
  - main