language: node_js
node_js: 
  - 12
after_success:
- npm run build
before_deploy:
- cd dist
deploy:
  provider: heroku
  email: andreapedro96@gmail.com
  on:
    branch: master
    repo: petretiandrea/personal-website
  api_key:
    secure: pBGIi41BK2L1f3+sNUwGHen5lyJ4xOThlwUr5K80kJRVP5UV0Rf+AKM7ndVuBg4WqLNOhLTqlMLfsbswjpgwJoojMAv0UaEZvqmpWX/3NF7x4rEgaQWSoXaPtJe0Hqb6UR684vY1dmizmF1uBYdt4o/srZlp26n9OsaeXGDf+8ef3aSig/eBaXsVyJ5wYNxqKaBMkkMtatVQ9N+5a7kK4Jx7skOOoH9rvcQwotiYNE8onL4U6OWHksYR6VbkOo5X4AIO5TEfdZ694vkCpgXbhtFMBW814X16pwwxML0qUyqr1JmShjVo5nXzubCaeg0jNKKQWKe8Pkxg29KeNZGPO2lX+jOnSJ3sS7QO2b1LjvqDvhi3GVxZLeWKVVo+iXNSikuUgDiXFEZlac0BPnvq/7dzC+2n5JDT6biDikKuFbRA6Jb+Rn0X9s8iU4Eh7E9SGdDPi8Irl32w4Op6CiQzMsRLZLtCplWNJ8gL2x5stD6edqL6/WSBgkvDrzz8q/Z/PKd0Wu+Tl0mtpRzItZuWwwKp87PIeklYOrz7b3LjY2a0/pohFAqmJhRFasTWa6KaME2YQ0DbrtDKMKwThOCLfeRh7VaWBAeSPV12PwXA8NEv3AxdtVfgvsZ2v5A2Gwdk3dRqVbDUhpK4roarx2PF15eg5lHjoQRGV8movey64t0=
